---
- hosts: avogadro
  become: true

  tasks:
  - name: Create network
    community.docker.docker_network:
      name: frontend-public

  - name: Create network
    community.docker.docker_network:
      name: auth-backend