---
- hosts: avogadro
  become: true

  tasks:
  - name: Create database, connect to network
    community.docker.docker_container:
      name: authentik-postgres
      hostname: authentik-postgres
      image: "docker.io/library/postgres:12-alpine"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d authentik-postgres -U {{ user.authentik.db.name }}"]
        start_period: 20s
        interval: 30s
        retries: 5
        timeout: 5s
      restart_policy: "unless-stopped"
      published_ports:
        - "8000:8000"
        - "9443:9443"
      volumes:
        - "database:/var/lib/postgresql/data"
        - "/var/run/docker.sock:/var/run/docker.sock"
      state: "started"
      keep_volumes: "yes"
      networks:
        - name: auth-backend
      environment:
        - POSTGRES_PASSWORD={{ user.authentik.db.password }}
        - POSTGRES_USER={{ user.authentik.db.name }}
        - POSTGRES_DB=authentik-postgres