---
- name: main - Network - Modify Hostname
  import_playbook: network/hostname.yaml

- name: main - Network - Modify IPV4 Forwarding
  import_playbook: kernel/net-forwarding.yaml

- name: main - storage tasks
  import_playbook: storage/storage-setup.yaml

- name: main - package tasks
  import_playbook: packages/install-packages.yaml

- name: main - login tasks
  import_playbook: login/user-group-creation.yaml

- name: main - Container tasksyes
  import_playbook: packages/install-docker.yaml

- name: main - Docker Daemon tasks
  import_playbook: app/docker/docker-daemon.yaml

- name: main - fail2ban tasks
  import_playbook: app/fail2ban/fail2ban.yaml  

- name: main - deploy portainer
  import_playbook: app/docker/containers/portainer/portainer.yaml

- name: main - deploy headscale
  import_playbook: app/docker/containers/headscale/headscale.yaml

- name: main - deploy headscale-ui
  import_playbook: app/docker/containers/headscale/headscale-ui.yaml  