---
- hosts: avogadro

  tasks:
<<<<<<< HEAD
=======
  - name: pull portainer
    community.docker.docker_image:
      name: portainer/portainer-ce:latest
      source: pull

>>>>>>> b77ed27eaa99ac7e3e69d5ddd0382083aed25616
  - name: Create a volume
    community.docker.docker_volume:
      name: portainer_data

  - name: Start portainer, connect to network
    community.docker.docker_container:
      name: portainer
      hostname: portainer
      restart_policy: "unless-stopped"
      image: "portainer/portainer-ce:latest"
      published_ports:
        - "8000:8000"
        - "9443:9443"
      volumes:
        - "portainer_data:/data"
        - "/var/run/docker.sock:/var/run/docker.sock"
      state: "started"
      keep_volumes: "yes"

