---
- hosts: avogadro

  tasks:
  - name: Create a volume
    community.docker.docker_volume:
      name: portainer_data

  - name: Start portainer, connect to network
    community.docker.docker_container:
      name: portainer
      hostname: portainer
      restart_policy: "unless-stopped"
      image: "portainer/portainer-ce:latest"
      exposed_ports:
        - 8000
        - 9443
      volumes:
        - "portainer_data:/data"
        - "/var/run/docker.sock:/var/run/docker.sock"
      state: "started"
      keep_volumes: "yes"
      networks:
        - name: frontend-public
