---
- hosts: avogadro
  become: true

  tasks:
    - name: Install required system packages
      ansible.builtin.apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt: name={{ item }} state=latest update_cache=yes
      loop: [ "docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Add "{{ user.apigban.name }}" to docker group
      ansible.builtin.user: 
        name: "{{ user.apigban.name }}"
        groups: docker
        append: yes