---
- hosts: avogadro
  become: yes

  tasks:
  - name: Force cache update
    ansible.builtin.apt:
      update_cache: yes
      
  - name: Install default packages
    ansible.builtin.apt: 
      name: "{{ default.apt_pkgs }}"
      state: latest

  - name: Install custom packages for avogadro group
    ansible.builtin.apt: 
      name: "{{ packages }}"
      state: latest